<?php

namespace TruckBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccidentCaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccidentCaseRepository extends EntityRepository
{
}
