<?php

namespace TruckBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccidentCaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccidentCaseRepository extends EntityRepository {
    
    public function findAllActiveCases() {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT c FROM TruckBundle:AccidentCase c WHERE c.status '
                . 'LIKE :active')->setParameter("active", "active");
        return $query->getResult();
    }
    
}
