<?php

namespace TruckBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DealerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealerRepository extends EntityRepository {
    
    public function findAllActiveDealers() {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT d FROM TruckBundle:Dealer d WHERE '
                . 'd.isActive = :active')->setParameter("active", "active");
        return $query->getResult();
    }

}
