<?php

namespace TruckBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MonitoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonitoringRepository extends EntityRepository {
    
    public function findMonitoringsByCaseId($caseId) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT m FROM TruckBundle:Monitoring m WHERE m.accidentCase'
                . ' = :caseId')->setParameter("caseId", $caseId);
        return $query->getResult();
    }     
    
    // all below to the end case report
    
    public function findFirstMonitoringStartByCaseId($caseId) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT m FROM TruckBundle:Monitoring m WHERE m.accidentCase'
                . ' = :caseId AND m.code = :code ORDER BY m.timeSave ASC')
                ->setMaxResults(1)
                ->setParameter("caseId", $caseId)
                ->setParameter("code", "START");
        return $query->getOneOrNullResult();
    }   
    
    public function findLastMonitoringEtaByCaseId($caseId) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT m FROM TruckBundle:Monitoring m WHERE m.accidentCase'
                . ' = :caseId AND m.code = :code ORDER BY m.timeSave DESC')
                ->setMaxResults(1)
                ->setParameter("caseId", $caseId)
                ->setParameter("code", "ETA");
        return $query->getOneOrNullResult();
    }       
    
    public function findLastMonitoringStrrByCaseId($caseId) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT m FROM TruckBundle:Monitoring m WHERE m.accidentCase'
                . ' = :caseId AND m.code = :code ORDER BY m.timeSave DESC')
                ->setMaxResults(1)
                ->setParameter("caseId", $caseId)
                ->setParameter("code", "STRR");
        return $query->getOneOrNullResult();
    }      
    
    public function findLastMonitoringEndByCaseId($caseId) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT m FROM TruckBundle:Monitoring m WHERE m.accidentCase'
                . ' = :caseId AND m.code = :code ORDER BY m.timeSave DESC')
                ->setMaxResults(1)
                ->setParameter("caseId", $caseId)
                ->setParameter("code", "END");
        return $query->getOneOrNullResult();
    }      
    
    public function findLastMonitoringRoByCaseId($caseId) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT m FROM TruckBundle:Monitoring m WHERE m.accidentCase'
                . ' = :caseId AND m.code = :code ORDER BY m.timeSave DESC')
                ->setMaxResults(1)
                ->setParameter("caseId", $caseId)
                ->setParameter("code", "RO");
        return $query->getOneOrNullResult();
    }   
    
    public function findLastMonitoringPgByCaseId($caseId) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT m FROM TruckBundle:Monitoring m WHERE m.accidentCase'
                . ' = :caseId AND m.code = :code ORDER BY m.timeSave DESC')
                ->setMaxResults(1)
                ->setParameter("caseId", $caseId)
                ->setParameter("code", "PG");
        return $query->getOneOrNullResult();
    }   
    
    public function findLastMonitoringCpgByCaseId($caseId) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT m FROM TruckBundle:Monitoring m WHERE m.accidentCase'
                . ' = :caseId AND m.code = :code ORDER BY m.timeSave DESC')
                ->setMaxResults(1)
                ->setParameter("caseId", $caseId)
                ->setParameter("code", "CPG");
        return $query->getOneOrNullResult();
    }     
    
}
