<?php

namespace TruckBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MonitoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonitoringRepository extends EntityRepository {
    
    public function findMonitoringsByCaseId($caseId) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT m FROM TruckBundle:Monitoring m WHERE m.accidentCase'
                . ' = :caseId')->setParameter("caseId", $caseId);
        return $query->getResult();
    }    
    
}
