<?php

namespace TruckBundle\Repository;

use Doctrine\ORM\EntityRepository;

//use Doctrine\ORM\Query\ResultSetMapping; //trainer

/**
 * MonitoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonitoringRepository extends EntityRepository {
    
    public function findMonitoringsByCaseId($caseId) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT m FROM TruckBundle:Monitoring m WHERE m.accidentCase'
                . ' = :caseId')->setParameter("caseId", $caseId);
        return $query->getResult();
    }    
    
//    public function findTimestampFirstStartMonitoringByCaseId($caseId) {
//        $em = $this->getEntityManager();
//        $rsm = new ResultSetMapping();
//        $query = $em->createNativeQuery('SELECT UNIX_TIMESTAMP(time_save) FROM monitoring WHERE accident_case_id'
//                . ' = ?', $rsm)->setParameter(1, $caseId);
//        return $query->getResult();
//    }       
    
}
