<?php

namespace TruckBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VehicleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleRepository extends EntityRepository {

    // unused. TODO to delete
    public function findVehiclesByDealerId($dealerId) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT v FROM TruckBundle:Vehicle v JOIN v.dealer d WHERE'
                        . ' d.id = :dealerId')->setParameter("dealerId", $dealerId);
        return $query->getResult();
    }

    public function findVehiclesByDealerIdQuery($dealerId) {
        $em = $this->getEntityManager();
        return $query = $em->createQuery('SELECT v FROM TruckBundle:Vehicle v JOIN v.dealer d WHERE'
                        . ' d.id = :dealerId')->setParameter("dealerId", $dealerId);
    }

}
