<?php

declare(strict_types=1);

namespace TruckBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * AccidentCaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccidentCaseRepository extends EntityRepository
{

    public function findAllCasesQuery()
    {
        $em = $this->getEntityManager();
        return $query = $em->createQuery('SELECT c FROM TruckBundle:AccidentCase c ORDER BY c.id ASC');
    }

    public function findAllActiveCases()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT c FROM TruckBundle:AccidentCase c WHERE c.status '
            . 'LIKE :active')->setParameter("active", "active");
        return $query->getResult();
    }

    public function findAllActiveCasesQuery()
    {
        $em = $this->getEntityManager();
        return $query = $em->createQuery('SELECT c FROM TruckBundle:AccidentCase c WHERE c.status '
            . 'LIKE :active ORDER BY c.id ASC')->setParameter("active", "active");
    }

    public function findAllInactiveCases()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT c FROM TruckBundle:AccidentCase c WHERE c.status '
            . 'LIKE :inactive')->setParameter("inactive", "inactive");
        return $query->getResult();
    }

    public function findAllInactiveCasesQuery()
    {
        $em = $this->getEntityManager();
        return $query = $em->createQuery('SELECT c FROM TruckBundle:AccidentCase c WHERE c.status '
            . 'LIKE :inactive ORDER BY c.id ASC')->setParameter("inactive", "inactive");
    }

    public function findAllCasesBy(
        ?string $companyName,
        ?string $damageDescription,
        ?string $truckLocation
    ): Query
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('ac');
        $qb->from('TruckBundle:AccidentCase', 'ac');
        $qb->innerJoin('ac.vehicle', 'v');
        $qb->orderBy('ac.id', 'ASC');


        if ($companyName !== null) {
            $qb->andWhere(
                $qb->expr()->like('v.companyName', ':companyName')
            );
            $qb->setParameter('companyName', "%$companyName%");
        }

        if ($damageDescription !== null) {
            $qb->andWhere(
                $qb->expr()->like('ac.damageDescription', ':damageDescription')
            );
            $qb->setParameter('damageDescription', "%$damageDescription%");
        }

        if ($truckLocation !== null) {
            $qb->andWhere(
                $qb->expr()->like('ac.location', ':truckLocation')
            );
            $qb->setParameter('truckLocation', "%$truckLocation%");
        }

        return $qb->getQuery();
    }
}
