<?php

declare(strict_types=1);

namespace TruckBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

use TruckBundle\Entity\Dealer;

/**
 * DealerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealerRepository extends EntityRepository
{

    public function findAllDealersQuery(): Query
    {
        $em = $this->getEntityManager();
        return $em->createQuery('SELECT d FROM TruckBundle:Dealer d ORDER BY d.id ASC');
    }

    public function findAllActiveDealersQuery(): Query
    {
        $em = $this->getEntityManager();
        return $em->createQuery('SELECT d FROM TruckBundle:Dealer d WHERE '
            . 'd.isActive = :active ORDER BY d.id ASC')->setParameter('active', Dealer::$dealerIsActive);
    }
}
