<?php

namespace TruckBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {
  
    // TODO
//    public function findUsersByPieceOfEmail($email) {
//        $em = $this->getEntityManager();
//        $query = $em->createQuery('SELECT u FROM TruckBundle:User u WHERE u.email '
//                        . 'LIKE :email')->setParameter("email", $email);
//        return $query->getResult();
//    }
//    
//    public function findUsersByPieceOfUsername($username) {
//        $em = $this->getEntityManager();
//        $query = $em->createQuery('SELECT u FROM TruckBundle:User u WHERE u.username '
//                        . 'LIKE :username')->setParameter("username", $username);
//        return $query->getResult();
//    }    

}
